//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Core.Framework.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BlobResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlobResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.Core.Framework.Storage.BlobResource", typeof(BlobResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read storage account settings from application configuration..
        /// </summary>
        public static string BlobConfigurationError {
            get {
                return ResourceManager.GetString("BlobConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred getting the path..
        /// </summary>
        public static string BlobContainerCreationError {
            get {
                return ResourceManager.GetString("BlobContainerCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while retrieving the versions..
        /// </summary>
        public static string BlobContainerGetSnapshotError {
            get {
                return ResourceManager.GetString("BlobContainerGetSnapshotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured creating copy..
        /// </summary>
        public static string BlobCreateCopyError {
            get {
                return ResourceManager.GetString("BlobCreateCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured creating new version..
        /// </summary>
        public static string BlobCreateSnapshotError {
            get {
                return ResourceManager.GetString("BlobCreateSnapshotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blob doesnot exists..
        /// </summary>
        public static string BlobDoesntExists {
            get {
                return ResourceManager.GetString("BlobDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}. Name: {1}. Path: {2}..
        /// </summary>
        public static string BlobErrorMessageFormat {
            get {
                return ResourceManager.GetString("BlobErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred getting the blob..
        /// </summary>
        public static string BlobGetBlobReferenceError {
            get {
                return ResourceManager.GetString("BlobGetBlobReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can only contain letters in lowercase, numbers, or the following special characters:  . + - ! * ` ( ) $..
        /// </summary>
        public static string BlobNameRegExMessage {
            get {
                return ResourceManager.GetString("BlobNameRegExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while commiting chunk upload..
        /// </summary>
        public static string CommitChunkUploadError {
            get {
                return ResourceManager.GetString("CommitChunkUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        public static string ContainerNameFormat {
            get {
                return ResourceManager.GetString("ContainerNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-z0-9]+(-[a-z0-9]+)*$.
        /// </summary>
        public static string ContainerNameRegEx {
            get {
                return ResourceManager.GetString("ContainerNameRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while getting blob service endpoint..
        /// </summary>
        public static string CreateCloudBlobClientError {
            get {
                return ResourceManager.GetString("CreateCloudBlobClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred deleting..
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while downloading chunks..
        /// </summary>
        public static string DownloadBlockListError {
            get {
                return ResourceManager.GetString("DownloadBlockListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred downloading..
        /// </summary>
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred retrieving metadata..
        /// </summary>
        public static string MetadataRetrieveError {
            get {
                return ResourceManager.GetString("MetadataRetrieveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more chunks of the uploaded file were found missing..
        /// </summary>
        public static string MissingBlocksError {
            get {
                return ResourceManager.GetString("MissingBlocksError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path must start with a letter or number, and can contain only letters in lowercase, numbers, and the dash (-) character. Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted.
        ///.
        /// </summary>
        public static string PathRegExMessage {
            get {
                return ResourceManager.GetString("PathRegExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating a chunk..
        /// </summary>
        public static string PutBlockError {
            get {
                return ResourceManager.GetString("PutBlockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading..
        /// </summary>
        public static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
    }
}
